-- MySQL Script generated by MySQL Workbench
-- Sun Aug 16 09:55:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webhw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webhw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webhw` DEFAULT CHARACTER SET utf8 ;
USE `webhw` ;

-- -----------------------------------------------------
-- Table `webhw`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webhw`.`user` ;

CREATE TABLE IF NOT EXISTS `webhw`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
   `name` VARCHAR(45) NOT NULL, 
  `email` VARCHAR(45) NULL DEFAULT NULL,
   `phone` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `create_time` datetime,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webhw`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webhw`.`item` ;

CREATE TABLE IF NOT EXISTS `webhw`.`item` (
  `iditem` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `price` DECIMAL(5) NULL DEFAULT NULL,
  `image` TEXT,
  `desc` VARCHAR(45) NULL DEFAULT NULL,
  `time` datetime,
  PRIMARY KEY (`iditem`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `webhw`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webhw`.`order` ;

CREATE TABLE IF NOT EXISTS `webhw`.`order` (
  `idorder` INT NOT NULL,
  `iduser` INT NULL DEFAULT NULL,
  `iditem` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idorder`),
  INDEX `orderitem_idx` (`iditem` ASC) VISIBLE,
  INDEX `itemuser_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `orderitem`
    FOREIGN KEY (`iditem`)
    REFERENCES `webhw`.`item` (`iditem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orderuser`
    FOREIGN KEY (`iduser`)
    REFERENCES `webhw`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
INSERT INTO `webhw`.`order` VALUES (1,1,1);
CREATE TABLE `webhw`.`order_item` (
        _id INTEGER NOT NULL AUTO_INCREMENT,
        orderid INTEGER,
        itemid INTEGER,
        count FLOAT NOT NULL,
        PRIMARY KEY (_id),
        FOREIGN KEY(orderid) REFERENCES `order` (idorder) ON DELETE cascade,
        FOREIGN KEY(itemid) REFERENCES item (iditem)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webhw`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webhw`.`cart` ;

CREATE TABLE IF NOT EXISTS `webhw`.`cart` (
  `idorder` INT NOT NULL,
  `iduser` INT NULL DEFAULT NULL,
  `iditem` INT NULL DEFAULT NULL,
  `count` DECIMAL(2) NULL DEFAULT NULL,
  PRIMARY KEY (`idorder`),
  INDEX `orderitem_idx` (`iditem` ASC) VISIBLE,
  INDEX `itemuser_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `cartitem`
    FOREIGN KEY (`iditem`)
    REFERENCES `webhw`.`item` (`iditem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cartuser`
    FOREIGN KEY (`iduser`)
    REFERENCES `webhw`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webhw`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webhw`.`image` ;

CREATE TABLE IF NOT EXISTS `webhw`.`image` (
  `idimage` INT NOT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `iditem` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idimage`))
ENGINE = InnoDB;

insert into  `webhw`.`image`(idimage,url,iditem)
values (2,"gaoshu.jpg",2);

insert into  `webhw`.`image`(idimage,url,iditem)
values (3,"g.jpg",3);

SET SQL_MODE=@OLD_SQL_MODE;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
INSERT INTO `item` VALUES (1,'同济纪念品纯棉卫衣红色',159,'1.png','暖暖的很贴心','2020-08-16 16:15:10'),(2,'花瓶',99,'100.png','我是个花瓶','2020-08-16 16:15:16'),(3,'同济围脖蓝色',59,'12.jpg','暖暖的很贴心','2020-08-16 16:15:26'),(4,'同济明信片西游记主题',13,'13.jpg','同济大学纪念品原创文艺手绘','2020-08-16 16:15:44'),(5,'同济大学出版社大学德语四级应试全攻略',35,'15.png','少年学德语吗','2020-08-16 16:16:05'),(6,'国立同济大学T恤简洁',59,'3.png','暖暖的很贴心','2020-08-16 16:16:29'),(7,'同济1907帆布袋蓝色加厚',20,'5.png','必备帆布袋','2020-08-16 16:16:50'),(8,'同济主题雨伞红色大号',45,'6.png','为你遮风挡雨','2020-08-16 16:17:09'),(9,'同济2018戊戌徽章',30,'7.png','纪念礼品校徽樱花季徽章礼盒胸针配饰logo','2020-08-16 16:17:24'),(10,'同济诗歌主题明信片大漠沙如雪',10,'9.jpg','同济大学纪念品原创文艺手绘','2020-08-16 16:17:47'),(11,'同济作业本小号',2,'bjb.jpg','物美价廉轻松笔记本办公用品','2020-08-16 16:17:55'),(12,'东方明珠木质模型小号',35,'dfmz.jpg','上海浦东特色旅游纪念礼品','2020-08-16 16:18:08'),(13,'同济帆布袋典雅白色',20,'fbd.jpg','樱花图书馆','2020-08-16 16:18:26'),(14,'同济明信片',5,'gwjd.jpg','同济大学纪念品原创文艺手绘','2020-08-16 16:18:37'),(15,'同济四季猫主题明信片',30,'mtj.jpg','同济大学纪念品四季猫原创文艺手绘','2020-08-16 16:18:56'),(16,'同济大学木质拼插模型',55,'mzpc.jpg','把学校带回家吧','2020-08-16 16:19:11'),(17,'同济食堂特供红烧大排',2.5,'tjdp.jpg','好吃','2020-08-16 16:19:31'),(18,'同济食堂特供铜火锅',60,'tjhg.jpg','温暖冬日','2020-08-16 16:19:46'),(19,'同济食堂特供中西面点',7.5,'tjmd.jpg','好吃','2020-08-16 16:20:05'),(20,'同济食堂特质打卤面条',8,'tjmt.jpg','emmm','2020-08-16 16:20:29'),(21,'同济青团豆沙馅',5,'tjqt.jpg','好吃','2020-08-16 16:20:43'),(22,'同济青团肉松馅',8,'tjqt2.jpg','好吃','2020-08-16 16:20:52'),(23,'同济大排档-小龙虾',30,'tjxlx.jpg','好吃','2020-08-16 16:21:15'),(24,'同济食堂特供月饼五仁',4,'tjyb.jpg','好吃','2020-08-16 16:21:30'),(25,'同济食堂特供鲜肉月饼',8,'tjyb2.jpg','一般','2020-08-16 16:21:42'),(26,'同济食堂特供樱花饼',3.5,'tjyhb.jpg','好吃','2020-08-16 16:21:56'),(27,'同济校徽徽章纪念品',30,'xz.jpg','纪念礼品校徽樱花季徽章礼盒胸针配饰logo','2020-08-16 16:22:17'),(28,'同济立体纸雕明信片',23.6,'zd.jpg','把学校带回家吧','2020-08-16 16:22:44');
select * from `item`;
INSERT INTO `user` VALUES (1,'frezcirno','2277861660@qq.com',NULL,'123456','2022-08-16 14:30:50');
INSERT INTO `webhw`.`cart` VALUES (1,1,1,1);
INSERT INTO `webhw`.`order_item` VALUES (1,1,1,1);

