-- MySQL Script generated by MySQL Workbench
-- Sun Aug 16 09:55:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webhw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webhw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webhw` DEFAULT CHARACTER SET utf8 ;
USE `webhw` ;

-- -----------------------------------------------------
-- Table `webhw`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webhw`.`user` ;

CREATE TABLE IF NOT EXISTS `webhw`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
   `name` VARCHAR(45) NOT NULL, 
  `email` VARCHAR(45) NULL DEFAULT NULL,
   `phone` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `create_time` datetime,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webhw`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webhw`.`item` ;

CREATE TABLE IF NOT EXISTS `webhw`.`item` (
  `iditem` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `price` DECIMAL(5) NULL DEFAULT NULL,
  `image` TEXT,
  `desc` VARCHAR(45) NULL DEFAULT NULL,
  `time` datetime,
  PRIMARY KEY (`iditem`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `webhw`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webhw`.`order` ;

CREATE TABLE IF NOT EXISTS `webhw`.`order` (
  `idorder` INT NOT NULL,
  `iduser` INT NULL DEFAULT NULL,
  `iditem` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idorder`),
  INDEX `orderitem_idx` (`iditem` ASC) VISIBLE,
  INDEX `itemuser_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `orderitem`
    FOREIGN KEY (`iditem`)
    REFERENCES `webhw`.`item` (`iditem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orderuser`
    FOREIGN KEY (`iduser`)
    REFERENCES `webhw`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
INSERT INTO `webhw`.`order` VALUES (1,1,1);
CREATE TABLE `webhw`.`order_item` (
        _id INTEGER NOT NULL AUTO_INCREMENT,
        orderid INTEGER,
        itemid INTEGER,
        count FLOAT NOT NULL,
        PRIMARY KEY (_id),
        FOREIGN KEY(orderid) REFERENCES `order` (idorder) ON DELETE cascade,
        FOREIGN KEY(itemid) REFERENCES item (iditem)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webhw`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webhw`.`cart` ;

CREATE TABLE IF NOT EXISTS `webhw`.`cart` (
  `idorder` INT NOT NULL,
  `iduser` INT NULL DEFAULT NULL,
  `iditem` INT NULL DEFAULT NULL,
  `count` DECIMAL(2) NULL DEFAULT NULL,
  PRIMARY KEY (`idorder`),
  INDEX `orderitem_idx` (`iditem` ASC) VISIBLE,
  INDEX `itemuser_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `cartitem`
    FOREIGN KEY (`iditem`)
    REFERENCES `webhw`.`item` (`iditem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cartuser`
    FOREIGN KEY (`iduser`)
    REFERENCES `webhw`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webhw`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webhw`.`image` ;

CREATE TABLE IF NOT EXISTS `webhw`.`image` (
  `idimage` INT NOT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `iditem` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idimage`))
ENGINE = InnoDB;

insert into  `webhw`.`image`(idimage,url,iditem)
values (2,"gaoshu.jpg",2);

insert into  `webhw`.`image`(idimage,url,iditem)
values (3,"g.jpg",3);

SET SQL_MODE=@OLD_SQL_MODE;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `item` VALUES (1,'男士卫衣',159,'1.png','暖暖的很贴心','2022-08-16 16:15:10'),
(2,'花瓶',99,'100.png','我是个花瓶','2022-08-16 16:15:16'),
(3,'绿联充电宝',429,'12.jpg','100W笔记本电脑专用,145W大功率快充,便携移动电源','2022-08-16 16:15:26'),
(4,'高等数学（同济版）',50,'13.jpg','高等数学教材','2022-08-16 16:15:44'),
(5,'大学德语四级应试全攻略（同济版）',35,'15.png','少年学德语吗','2022-08-16 16:16:05'),
(6,'NVIDIA英伟达盒装RTX4090显卡24G',8990,'3.png','24G显存','2023-05-16 16:16:29'),
(7,'大疆入门级遥控无人机',698,'5.png','无刷电机，高清电调摄像头','2022-08-16 16:16:50'),
(8,'2022李永乐复习全书基础篇',54,'6.png','22考研数学','2023-04-16 16:17:09'),
(9,'大疆DJI专业摄像机',43888,'7.png','5.5英寸，三轴防抖，专业级','2022-08-16 16:17:24'),
(10,'casio电子手表男士',866,'9.jpg','GA-110,防震防磁,全自动日历等','2022-08-16 16:17:47'),
(11,'纸质笔记本',6,'bjb.jpg','物美价廉轻松笔记本办公用品','2022-08-16 16:17:55'),
(12,'Jeep山地自行车',679,'zxc.jpg','男女式变速单车镁合金油刹27.5寸','2022-08-16 16:18:08'),
(13,'帆布袋典雅白色',20,'fbd.jpg','典雅','2022-08-16 16:18:26'),
(14,'多功能哑铃',32,'yl.jpg','六角哑铃套装','2022-08-16 16:18:37'),
(15,'雅戈尔短袖衬衫',68,'chenshan.jpg','男式,商务,正装','2022-08-16 16:18:56'),
(16,'沙宣柔顺去屑洗发水',99,'xfs.jpg','美妆护肤','2022-08-16 16:19:11'),
(17,'良品铺子红豆三明治',18,'smz.jpg','好吃滴','2022-08-16 16:19:31'),
(18,'沙宣男士哑光蓬松定型发泥',50,'fani.jpg','自然蓬松,清香型,持久定型','2022-08-16 16:19:46'),
(19,'kdst拳击沙袋',99,'qjsd.jpg','减压，立式，沙袋','2022-08-16 16:20:05'),
(20,'激光投影虚拟镭射键盘',299,'xnjp.jpg','无线蓝牙无线3d投屏触控','2022-08-16 16:20:29'),
(21,'李宁握力器',26,'wlq.jpg','电子款计数','2022-08-16 16:20:43'),
(22,'露营收纳箱',23,'snx.jpg','车载，折叠','2022-08-16 16:20:52'),
(23,'电蚊拍充电式',25,'dwp.jpg','家用，锂电池，超强力灭蚊','2022-08-16 16:21:15'),
(24,'飞利浦机械键盘',109,'jxjp.jpg','办公，有线','2022-08-16 16:21:30'),
(25,'折叠水桶',13,'zdst.jpg','户外钓鱼，车载洗车桶','2022-08-16 16:21:42'),
(26,'新飞迷你小型冰箱',139,'xxbx.jpg','学生宿舍，车载家用','2022-08-16 16:21:56'),
(27,'小型多功能电煮锅',100,'dzg.jpg','智能款，5款火力，700W','2022-08-16 16:22:17'),
(28,'迷你小电视',156,'monixds.jpg','触摸屏，易操作，usb充电','2022-08-16 16:22:44');
INSERT INTO `webhw`.`cart` VALUES (1,1,1,1);
INSERT INTO `webhw`.`order` VALUES (1,2,1);
INSERT INTO `webhw`.`order_item` VALUES (1,1,1,1);
INSERT INTO `user` VALUES (1,'wz','1726307829@qq.com',NULL,'111','2023-05-16 14:30:50');
select * from `order`
